### ISSUE TITLE
Atlas migration system

### ISSUE THREAD

**Issue by kevbook** [pricelastic/postgresql#2]
### `altas.hcl` file

```hcl
locals {
  host = env("POSTGRES_HOST", "0.0.0.0")
  db   = env("POSTGRES_DB", "postgres")
  user = env("POSTGRES_USER", "postgres")
  pass = env("POSTGRES_PASSWORD", "postgres")
}

// Common settings
env {
  // Target database URL using values from locals
  url = "postgres://${locals.user}:${locals.password}@${locals.host}:${locals.db}"

  // Dev database url (https://atlasgo.io/concepts/dev-database)
  dev = "postgres://postgres:postgres@0.0.0.0:5432/atlas?sslmode=disable"
  src = "file://schemas/" // Schema definitions
  migration {
    dir = "file://migrations"
  }
  lint {
    latest = 1
    git { dir = "./" }
  }
}

// Local environment
env "local" {
  // Common settings
  // // Declare schema definitions
  // src = "file://schemas/"

  // migration {
  //   dir = "file://migrations"
  // }

  //  lint {
  //   latest = 1
  //   git {    dir = "./"   }
  // }
}

// env "external" {}
```

### `docker-compose`

```yaml
  # -------------------------------------------------------
  # Host: http://0.0.0.0:5050
  # -------------------------------------------------------
  atlas:
    init: true
    image: arigaio/atlas:latest
    # depends_on:
    #   - postgres
    volumes:
      # Mount local directory to persist data
      - ${PWD}/migrations:/migrations
    command: >
      migrate apply
      --url mysql://root:pass@mysql:3306/test
```
